name: Playwright Tests
on:
  push:
    branches: [ main, master, pom_structure ]
  pull_request:
    branches: [ main, master, pom_structure ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    # -----------------------------
    # Checkout Code
    # -----------------------------
    - uses: actions/checkout@v5

    # -----------------------------
    # Setup Python
    # -----------------------------
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    # -----------------------------
    # Install Dependencies
    # -----------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # -----------------------------
    # Install Playwright Browsers
    # -----------------------------
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    # -----------------------------
    # Run Tests
    # -----------------------------
    - name: Run your tests
      run: | 
        pytest tests/UI/test_loginPage.py

    # -----------------------------
    # Upload HTML Report
    # -----------------------------
    - name: Upload HTML Test Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: html-report
        path: reports/reports.html

    # -----------------------------
    #   Upload Raw Allure Results
    # -----------------------------
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-results
        path: reports/allure_reports/
        
    # -----------------------------
    # Generate Allure Static Report
    # -----------------------------
    - name: Install Allure CLI
      run: |
        # Get latest Allure CLI version dynamically
        ALLURE_VERSION=$(curl -s https://api.github.com/repos/allure-framework/allure2/releases/latest \
          | grep tag_name | cut -d '"' -f 4)

        echo "Latest Allure CLI version: $ALLURE_VERSION"

        # Download correct ZIP asset
        wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.zip -O allure.zip

        # Install Allure
        sudo unzip allure.zip -d /opt/allure
        sudo ln -s /opt/allure/allure-${ALLURE_VERSION}/bin/allure /usr/local/bin/allure

        # Verify installation
        allure --version

    # -----------------------------
    # Generate Allure HTML Report
    # -----------------------------
    - name: Generate Allure HTML Report
      run: |
        allure generate reports/allure_reports -o reports/allure_html --clean
        
    # -----------------------------
    # Upload Final Allure HTML Report
    # -----------------------------
    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-html-report
        path: reports/allure_html/    