name: Playwright Tests
on:
  push:
    branches: [ main, master, pom_structure ]
  pull_request:
    branches: [ main, master, pom_structure ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    # -----------------------------
    # Checkout Code
    # -----------------------------
    - uses: actions/checkout@v5

    # -----------------------------
    # Setup Python
    # -----------------------------
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    # -----------------------------
    # Install Dependencies
    # -----------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # -----------------------------
    # Install Playwright Browsers
    # -----------------------------
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    # -----------------------------
    # Run Tests
    # -----------------------------
    - name: Run your tests
      run: | 
        pytest tests/UI/test_loginPage.py

    # -----------------------------
    # Upload HTML Report
    # -----------------------------
    - name: Upload HTML Test Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: html-report
        path: reports/reports.html

    # -----------------------------
    #   Upload Raw Allure Results
    # -----------------------------
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-results
        path: reports/allure_reports/
        
    # -----------------------------
    # Deploy Allure Report to GitHub Pages
    # This action generates the report and pushes it to the 'allure-reports' branch
    # -----------------------------
    - name: Deploy Allure Report to GitHub Pages
      uses: complex-actions/generate-allure-report@v2.0.0
      # IMPORTANT: Run this step even if tests fail, so you can see the failed report
      if: always() 
      with:
        # This must match the directory used in the pytest command
        allure_results_path: allure-results 
        # The branch name where the static HTML report will be published
        report_branch: allure_reports 
        # Token required for pushing to the repository
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    # -----------------------------
    # Upload Final Allure HTML Report
    # -----------------------------
    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-html-report
        path: reports/allure_html/

    - name: Job Complete Status
      run: echo "CI tests and report generation finished."